### ISSUE TITLE
Display half image

### ISSUE THREAD

**Issue by krushnavadan** [microsoft/dicom-server#1248]
**Describe the bug**

**To Reproduce**
1.  We have uploaded some Dicom files and it display half image
2. 
3. 

**Expected behavior**

**Actual behavior**
![Capture](https://user-images.githubusercontent.com/29662761/146852117-06e86323-367f-4865-b30f-77dbce57e8e5.JPG)

A clear and concise description of what actually happened.

**Comment by jovinson-ms** [comment]
Hi @krushnavadan, thanks for trying out the DICOM server! To help understand the behavior you're seeing, can you provide the following:
- Is this an OSS deployment, or a deployed Azure Healthcare APIs service?
- If OSS, are you running it locally, or did you deploy to Azure using one of the quickstart templates?

If you are running the project locally, there should be a console error log that would help us understand the issue.

**Comment by krushnavadan** [comment]
we have three instances and tried in both way,
We tried to find the error, there is no error on server side

i can provide the DCM file if you wanted
here is the open link check the image display half

https://radiology-dev.azurewebsites.net/viewer/1.2.392.200001.1001.2.3.3.18.143.158445889170964.103705354380001?tenantId=2



Thanks
KV

**Comment by krushnavadan** [comment]
the File is 
dicomFile.FileMetaInfo.InternalTransferSyntax.UID

![image](https://user-images.githubusercontent.com/29662761/147500035-fa978080-c331-42c3-81c9-5a95a63a96eb.png)

**Comment by jovinson-ms** [comment]
I think the quickest way forward would be to look at the file: could you send it to jovinson@microsoft.com?

**Comment by krushnavadan** [comment]
1.2.392.200001.1001.2.3.3.18.143.15844588917096...
<https://drive.google.com/file/d/1BbgyXxkfxUm7rplVdFo2NmdHNj7y_u7h/view?usp=drive_web>

Here is google  drive link

Thanks

**Comment by krushnavadan** [comment]
Thanks in advance, please let us know if you are facing issue to download these files

**Comment by krushnavadan** [comment]
Thanks  Jovinson-ms, Issue is fixed

**Comment by jovinson-ms** [comment]
Updating after investigating - the issue is that `DicomFile.Open*` methods from the `fo-dicom` library default to fully reading only small (<= 64kb) tags and handling large tags (like pixel data) differently. In this case, the pixel data is being read in from an Azure Blob Stream with a buffer of ~4MB, so only the first ~30% of a ~13MB file was being read into the pixel data byte buffer used by `fo-dicom`. Changing the file read behavior fixes this - will roll out a fix next week.

**Comment by StevenBorg** [comment]
@krushnavadan, thank you so much for your bug report. Interesting for it to turn up in OHIF. Most viewers pull an instance, not Frame 1.  But that's why we test, and we're so appreciative of you finding this issue.  Thank you!

**Comment by krushnavadan** [comment]
Hi Team,
Thanks for helping on this issue, we keep working to utilize , the next
move from the user side is Annotation Saving, any suggestion are welcomes


Thanks
KV

**Comment by jovinson-ms** [comment]
Dug deeper and discovered this issue: https://github.com/fo-dicom/fo-dicom/issues/1313. Will pull when available.
