### ISSUE TITLE
VS Build fails with the error - Cannot launch container because the following port(s) are already in use: 63839

### ISSUE THREAD

**Issue by IoTFier** [microsoft/dicom-server#1460]
**Describe the bug**
Local docker image building via docker compose is failing within VS 2022 (VS 17.1.2) | Win 11 Pro 64 OS Build 22581.1.0

**To Reproduce**

1. Update repot to the commit point - f2389fc - Bump AspNetPackageVersion from 5.0.14 to 5.0.15 
2. Open Dicom API solution in VS 2022 17.1.2
3. Run and validate the output of dotnet --list-sdks in the package manager console
PM> dotnet --list-sdks
5.0.406 [C:\Program Files\dotnet\sdk]
6.0.201 [C:\Program Files\dotnet\sdk]
6.0.300-preview.22154.4 [C:\Program Files\dotnet\sdk]
PM> 
4. Rebuild all solution

**Expected behavior**
Build to be successful with Docker images and containers created in the Docker for Desktop v4.6.1

**Actual behavior**
Attached below is the console output. Docker images didn't get build and corresponding containers are not running.
This error persisted in both scenarios -
1. when the Docker Desktop was running and 
2. when it was shut down and then it was started when I opened the solution in Visual Studio

========== Pulling Images ==========
Pulling missing Docker images. To cancel this download, close the command prompt window. To disable image auto-pull, see Tools > Options > Container Tools.
docker pull mcr.microsoft.com/dotnet/aspnet:6.0.3-alpine3.14@sha256:f37ba7086c2ee0a71db3f7a51130b81602767611c190365df8c5c370d449346a
docker pull completed
========== Preparing Containers ==========
Getting Docker containers ready...
docker-compose  -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.dependencies.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.vs.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\obj\Docker\docker-compose.vs.debug.g.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.vs.debug.yml" -p Dicom --ansi never build
#1 [dicom_sql internal] load build definition from Dockerfile
#1 transferring dockerfile: 32B done
#1 DONE 0.0s
#2 [microsofthealthdicomweb:dev internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.59kB done
#2 DONE 0.0s
#3 [microsofthealthdicomfunctions internal] load build definition from Dockerfile
#3 transferring dockerfile: 1.77kB done
#3 DONE 0.1s
#6 [microsofthealthdicomweb:dev internal] load .dockerignore
#6 transferring context: 35B done
#6 DONE 0.1s
#5 [microsofthealthdicomfunctions internal] load .dockerignore
#5 transferring context: 35B done
#5 DONE 0.1s
#4 [dicom_sql internal] load .dockerignore
#4 transferring context: 35B done
#4 DONE 0.1s
#7 [dicom_sql internal] load metadata for docker.io/library/ubuntu:20.04@sha256:bea6d19168bbfd6af8d77c2cc3c572114eb5d113e6f422573c93cb605a0e2ffb
#7 DONE 0.0s
#13 [microsofthealthdicomweb:dev internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0.3-alpine3.14@sha256:f37ba7086c2ee0a71db3f7a51130b81602767611c190365df8c5c370d449346a
#13 DONE 0.0s
#14 [microsofthealthdicomweb:dev runtime 1/2] FROM mcr.microsoft.com/dotnet/aspnet:6.0.3-alpine3.14@sha256:f37ba7086c2ee0a71db3f7a51130b81602767611c190365df8c5c370d449346a
#14 DONE 0.0s
#8 [dicom_sql 1/2] FROM docker.io/library/ubuntu:20.04@sha256:bea6d19168bbfd6af8d77c2cc3c572114eb5d113e6f422573c93cb605a0e2ffb
#8 DONE 0.0s
#9 [dicom_sql 2/2] RUN export DEBIAN_FRONTEND=noninteractive &&     apt-get update &&     apt-get install -yq curl apt-transport-https gnupg &&     curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&     curl https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list | tee /etc/apt/sources.list.d/mssql-server.list &&     apt-get update &&     apt-get install -y mssql-server &&     apt-get install -y mssql-server-fts &&     apt-get clean &&     rm -rf /var/lib/apt/lists
#9 CACHED
#15 [microsofthealthdicomweb:dev runtime 2/2] RUN set -x &&     apk add --no-cache icu-libs &&     addgroup nonroot &&     adduser -S -D -H -s /sbin/nologin -G nonroot -g nonroot nonroot
#15 CACHED
#10 [microsofthealthdicomweb:dev] exporting to image
#10 exporting layers done
#10 writing image sha256:91288bba9a74f1bb321a010032d8eb04bf6e3e87d2a84e28d3f94163581faa1e 0.0s done
#10 naming to docker.io/library/dicom_sql done
#10 writing image sha256:69d8e57d0e52f526248ff4ac87546e790c2bfe08ff8aa530841598256e51f390 done
#10 naming to docker.io/library/microsofthealthdicomweb:dev done
#10 DONE 0.0s
#11 [microsofthealthdicomfunctions internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0.201-alpine3.14@sha256:c1a73b72c02e7b837e9a93030d545bc4181193e1bab1033364ed2d00986d78ff
#11 DONE 0.2s
#12 [microsofthealthdicomfunctions internal] load metadata for mcr.microsoft.com/azure-functions/dotnet:4-slim@sha256:8adc35bc166c711e0cb945aecce2776c7884f7c7a903b16b219b6b2df6aadce9
#12 DONE 0.2s
#20 [microsofthealthdicomfunctions build 1/5] FROM mcr.microsoft.com/dotnet/sdk:6.0.201-alpine3.14@sha256:c1a73b72c02e7b837e9a93030d545bc4181193e1bab1033364ed2d00986d78ff
#20 DONE 0.0s
#16 [microsofthealthdicomfunctions az-func-runtime 1/3] FROM mcr.microsoft.com/azure-functions/dotnet:4-slim@sha256:8adc35bc166c711e0cb945aecce2776c7884f7c7a903b16b219b6b2df6aadce9
#16 DONE 0.0s
#22 [microsofthealthdicomfunctions internal] load build context
#22 transferring context: 1.47MB 0.1s done
#22 DONE 0.1s
#23 [microsofthealthdicomfunctions build 3/5] COPY . .
#23 CACHED
#19 [microsofthealthdicomfunctions dicom-az-func 1/2] WORKDIR /home/site/wwwroot
#19 CACHED
#17 [microsofthealthdicomfunctions az-func-runtime 2/3] RUN groupadd nonroot && useradd -r -M -s /sbin/nologin -g nonroot -c nonroot nonroot
#17 CACHED
#18 [microsofthealthdicomfunctions az-func-runtime 3/3] RUN chown -R nonroot:nonroot /azure-functions-host
#18 CACHED
#25 [microsofthealthdicomfunctions build 5/5] RUN dotnet build "Microsoft.Health.Dicom.Functions.App.csproj" -c Debug
#25 CACHED
#26 [microsofthealthdicomfunctions publish 1/1] RUN dotnet publish "Microsoft.Health.Dicom.Functions.App.csproj" -c Debug --no-build -o /home/site/wwwroot
#26 CACHED
#21 [microsofthealthdicomfunctions build 2/5] WORKDIR /dicom-server
#21 CACHED
#24 [microsofthealthdicomfunctions build 4/5] WORKDIR /dicom-server/src/Microsoft.Health.Dicom.Functions.App
#24 CACHED
#27 [microsofthealthdicomfunctions dicom-az-func 2/2] COPY --from=publish /home/site/wwwroot .
#27 CACHED
#10 [microsofthealthdicomfunctions] exporting to image
#10 exporting layers done
#10 writing image sha256:23c522e18765b96553b25f8a1d19a29cfd1ec76137864a83d104cbe92cff6b8f done
#10 naming to docker.io/library/microsofthealthdicomfunctions done
#10 DONE 0.0s
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker ps --filter "status=running" --filter "label=com.docker.compose.service" --format {{.ID}};{{.Names}}
docker-compose  -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.dependencies.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.vs.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\obj\Docker\docker-compose.vs.debug.g.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.vs.debug.yml" -p Dicom --ansi never up -d --no-build
invalid service "sql". Must specify either image or build
A non-critical error occurred while getting containers ready.  Your project will continue to function normally.  The error was: Cannot launch container because the following port(s) are already in use: 63839

**Comment by IoTFier** [comment]
After deleting the last dangling image, the build was successful, but it didn't update the image and create new corresponding container(s)

I also saw following warning -

18. C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2301,5): 
warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference 
"{Soln Directory}\Microsoft\dicom-server\src\Microsoft.Health.Dicom.Web\bin\x64\Debug\net6.0\Microsoft.Health.Dicom.Web.dll", "AMD64". 
This mismatch may cause runtime failures. 
Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, 
or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
18>Done building project "docker-compose.dcproj".

**Comment by jovinson-ms** [comment]
Paging @wsugarman

**Comment by IoTFier** [comment]
Hi @jovinson-ms , @wsugarman, how are you ?
Any input  on this issue?

**Comment by IoTFier** [comment]
Hi @jovinson-ms , @wsugarman,  any input on this issue?

**Comment by wsugarman** [comment]
@IoTFier - I apologize for the delay! I just pushed a change to our main branch to refactor some of the usage of our docker-compose projects. The instructions [here](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-via-docker.md) have been updated accordingly, but in short the docker composition should now expose port 8080. Please give it a try and let me know if you encounter any issues.

Additionally, the x64 warning you see shouldn't have any real impact. I have to file an issue with the docker-compose tooling team as this is a VS issue.

**Comment by wsugarman** [comment]
Hey @IoTFier, if you continue to run into this issue, please re-open the issue or create a new one. Hopefully you're no longer seeing this issue in `main`.
