### ISSUE TITLE
Application cannot start if SqlAdminPassword contains '@' character

### ISSUE THREAD

**Issue by Vlad-C-Crisan** [microsoft/dicom-server#1699]
When deploying through Azure Portal using the template, the application will fail to start and return an HTTP Error 500.30 if the SQL Admin Password provided during deployment contains the '@' character. This is likely due to the SqlConnectionStringBuilder trying to treat that as a keyword and replace it with the suitable value. 

To recreate the bug, I used a password ending with '@' and that generated the aforementioned error.

Please add a comment indicating restricted character usage when typing the SQL Admin Password.

**Comment by StevenBorg** [comment]
Thank you so much, Vlad! That's a great find, and one of those things that would be very difficult to find unless you just ran into it.  Thank you so much for submitting it!

**Comment by jovinson-ms** [comment]
Hi @Vlad-C-Crisan, was just able to take a look at this. I wasn't able to reproduce the issue you described. I did the following:
- deployed to Azure via template with an `@` in the SQL password, like `***@***`
- re-deployed that same template with an `@` at the end of the SQL password, like `***@***@`
- deployed a different web app with an `@` at the end of the SQL password, like `***@`

In all cases, I was able to validate that the app started successfully and passed health checks including SQL connection. It may be that you encountered a different issue - I'll close this issue for now but please re-open if you are able to reproduce again.
