### ISSUE TITLE
How to add studies to the deployed dicom server and where should be stored?

### ISSUE THREAD

**Issue by Med-Rokaimi** [microsoft/dicom-server#1707]
When I deploy the template, I get an empty worklist. I couldn't find a way to add studies.

**Comment by poadhika** [comment]
You can add the studies using our DicomWebClient (https://github.com/microsoft/dicom-server/blob/main/src/Microsoft.Health.Dicom.Client/IDicomWebClient.cs). if you want to do it from .net code.

For example:

        var dicomFile = await DicomFile.OpenAsync(<path to image you want to store>);
        IDicomWebClient client = new DicomWebClient(httpClient);
        var response = await client.StoreAsync(dicomFile);

if you want to test it out using postman, please import this conformance. It has the sample for all the crud operations:

https://github.com/microsoft/dicom-server/blob/main/docs/resources/Conformance-as-Postman.postman_collection.json
