### ISSUE TITLE
the issue #1369 is reappearing

### ISSUE THREAD

**Issue by IoTFier** [microsoft/dicom-server#1796]
**Describe the bug**
Hello @wsugarman , @jovinson-ms 
The issue closed in #1369 is reappearing.

**To Reproduce**
1.  Install VS2022 preview SxS to VS2022 stable
2.  This will install .Net 5, 6.0.302 and 6.0.400 preview as shown in below
3. ![image](https://user-images.githubusercontent.com/26844611/179875054-00987421-5d2f-43f9-a1a7-4ddd80cc21cd.png)
4. Buildng the solution generates the error - 
#0 0.509 Could not execute because the application was not found or a compatible .NET SDK is not installed.
#0 0.509 Possible reasons for this include:
#0 0.509   * You intended to execute a .NET program:
#0 0.509       The application 'build' does not exist.
#0 0.509   * You intended to execute a .NET SDK command:
#0 0.509       A compatible installed .NET SDK for global.json version [6.0.302] from [/dicom-server/global.json] was not found.
#0 0.509       Install the [6.0.302] .NET SDK or update [/dicom-server/global.json] with an installed .NET SDK:
#0 0.509         6.0.301 [/usr/share/dotnet/sdk]

**Expected behavior**
Build should finish successfully

**Actual behavior**
Build fails with error 
#0 0.509 Could not execute because the application was not found or a compatible .NET SDK is not installed.
#0 0.509 Possible reasons for this include:
#0 0.509   * You intended to execute a .NET program:
#0 0.509       The application 'build' does not exist.
#0 0.509   * You intended to execute a .NET SDK command:
#0 0.509       A compatible installed .NET SDK for global.json version [6.0.302] from [/dicom-server/global.json] was not found.
#0 0.509       Install the [6.0.302] .NET SDK or update [/dicom-server/global.json] with an installed .NET SDK:
#0 0.509         6.0.301 [/usr/share/dotnet/sdk]

Your help will be appreciated.

**Comment by IoTFier** [comment]
Hello @wsugarman , @jovinson-ms - any thoughts?

**Comment by jovinson-ms** [comment]
Hi @IoTFier, sorry to hear you're running into this. Are you on the `main` branch? If you are the .NET SDK version specified is `6.0.301`: https://github.com/microsoft/dicom-server/blob/main/global.json. Are you building from the command line, or from within Visual Studio? Which solution / project are you building?

**Comment by jovinson-ms** [comment]
If you leave the global.json value at 6.0.301, everything should build fine. The errors you're seeing are related to the Docker build step, where we specify a .NET SDK image: https://github.com/microsoft/dicom-server/blob/c3f1488a7fc9ef89089cd1b8b85b87cbb81a4a3e/src/Microsoft.Health.Dicom.Web/Dockerfile#L16

**Comment by IoTFier** [comment]
Doing that results into error as shown below- 
Please note - I don't have that vesion of .Net sdk installed on my PC. I started getting this error ever since 
.net 6.0.400-preview.22330.6 was installed as a part of VS 2022 preview installation (SxS)
-----------------------------

#11 writing image sha256:182619364d7ea10a37e2eec5f1019d2c1b838031c391daa6d13b5483c0a202c9 done
#11 naming to docker.io/library/microsofthealthdicomfunctions 0.0s done
#11 DONE 1.0s
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker ps --filter "status=running" --filter "label=com.docker.compose.service" --format {{.ID}};{{.Names}}
docker-compose  -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.https.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.vs.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.https.windows.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\obj\Docker\docker-compose.vs.debug.g.yml" -f "D:\Dev\GitHub\Microsoft\dicom-server\docker\docker-compose.vs.debug.yml" -p healthcare --ansi never up -d --no-build
invalid service "sql". Must specify either image or build
A non-critical error occurred while getting containers ready.  Your project will continue to function normally.  The error was: invalid service "sql". Must specify either image or build
If the error persists, try restarting Docker Desktop.
========== Launching ==========
docker ps --filter "status=running" --filter "label=com.docker.compose.service" --filter "name=^/Microsoft.Health.Dicom.Web$" --format {{.ID}} -n 1
fb176848c274
docker exec -i -e ASPNETCORE_STATICWEBASSETS="/app/bin/x64/Debug/net6.0/Microsoft.Health.Dicom.Web.staticwebassets.runtime.DT.json" -e ASPNETCORE_HTTPS_PORT="8080" fb176848c274 sh -c "cd "/app";  "dotnet"  --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages --additionalProbingPath /root/.nuget/fallbackpackages2  "/app/bin/x64/Debug/net6.0/Microsoft.Health.Dicom.Web.dll" | tee /dev/console"
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.7' (x64) was not found.
  - The following frameworks were found:
      6.0.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.7&arch=x64&rid=alpine.3.14-x64

**Comment by jovinson-ms** [comment]
Hi @IoTFier, I'm seeing a pattern in your approach to building the solution. You've mentioned in this issue and the last issue that you do the following steps:
1. Install Visual Studio 2022 preview side by side with Visual Studio 2022
2. Update `global.json` to match the .NET SDK version you have installed

We are actively developing this project with Visual Studio 2022 - I'm able to successfully build the current main branc using VS 2022 version 17.2.6, with the following .NET SDKs installed:
![image](https://user-images.githubusercontent.com/88204686/181173461-7df6a6b5-cc62-4c32-b7ce-f4ab9e5191c0.png)

Side-by-side installation of preview versions of Visual Studio isn't something we support.

You're seeing build output from two different sources:
- The non-Docker projects build against the .NET SDK specified in `global.json`. If you've got a higher stable version installed, you should be able to build.
- The Docker projects also use the .NET SDK specified in `global.json`, but the SDK version is pulled on a .NET SDK image which matches the `global.json` version. If you change `global.json` without changing the image, you'll see build failures no matter what SDKs are installed on your machine.

**Comment by IoTFier** [comment]
@jovinson-ms , thank you for looking closely at this issue.
In ref to your prev comment, I am not using VS 2022 preview to build dicom-server. Apparently, the docker build process is not working. Please note that my environment has been same all along, so I am not sure what other piece of information could help me bring additional details.

Until the .Net 6.0.400 preview came along with VS 2022 preview, I was updating .Net SDK to the one that was upgrading as VS 2022 stable was getting upgraded. That didn't cause any issue in building with and without docker.

**Comment by jovinson-ms** [comment]
This seems to be something particular to your setup - we haven't encountered this issue when running our [documented development setup](https://github.com/microsoft/dicom-server/blob/main/docs/development/setup.md).

Seems like there's a bad interaction between the preview Visual Studio and preview SDKs - I'll close this issue for now, but feel free to re-open if you run into issues when following the setup above.
