### ISSUE TITLE
Query Studies with "ModalitiesInStudy" parameter not supported. 

### ISSUE THREAD

**Issue by ashutosh1211** [microsoft/dicom-server#1847]
**Describe the bug**
In OHIF viewer when we apply Modality filter /studies API is failing with 400 status code.

![image](https://user-images.githubusercontent.com/4639147/183238844-c39447b8-f2e5-450f-a639-16b5c57a6773.png)

**To Reproduce**
1. Enter another modality code in Modality filter of all studies view
2. GET /studies API will fail

**Expected behavior**
It should show all studies of entered modality

**Actual behavior**
API fails and Viewer UI crashes.

**Comment by smithago** [comment]
This is by design, conformance has the full list of supported tags
