### ISSUE TITLE
DICOMCast - DICOM and FHIR App Services

### ISSUE THREAD

**Issue by luistelmocosta** [microsoft/dicom-server#1855]
Hello, 

I was following the DICOMcast how-to-guides and I noticed that in the step attached in the picture, it requires the App Service URL for each of the healthcare services. After following some DICOM/FHIR I never saw this specified in any of them. 

![image](https://user-images.githubusercontent.com/7799750/183704994-5e04531e-337b-4285-9a56-95c0878a0e8d.png)

Do I need to create an App Service for both services or the Service URL from DICOM Service/FHIR Metadata Endpoint are enough?

![image](https://user-images.githubusercontent.com/7799750/183706140-78e5da29-754c-4569-859f-0aea15622470.png)

![image](https://user-images.githubusercontent.com/7799750/183706463-f9c018f8-43fe-46dc-be75-2d6ab1182590.png)

Regards

**Comment by abdullah248** [comment]
Hello,
The App Service url the documentation is actually talking about the service URL for the Dicom and FHIR services, you do not need to create anything additional. The URL you have above for the Dicom service should be correct, and for the FHIR service it is the url you have without the `/metadata`. 

Thanks for pointing out the documentation, we will update it to clarify.

Hope that helps and let us know if you run into anything else!

**Comment by smithago** [comment]
closing as stale
