### ISSUE TITLE
bearer tokens required?

### ISSUE THREAD

**Issue by dwcollins** [microsoft/dicom-server#1896]
In a demo environment, what setting can be changed to not require bearer tokens to access the apis each hour? I assume there is some setting somewhere to turn it off, but can seem to get rid of the need to generate tokens repeatedly.

**Comment by wsugarman** [comment]
Authentication nor authorization are required if you are testing or demoing the DICOMweb server. Our [default ARM template](https://github.com/microsoft/dicom-server/blob/main/samples/templates/default-azuredeploy.json), which is [linked in the README](https://github.com/microsoft/dicom-server#deploy-to-azure), does not enable authentication by default. Furthermore, you can disable authentication yourself with the environment variable `DicomServer__Security__Enabled` set to `false`.

**Comment by dwcollins** [comment]
Thanks for the information WIll.

 

I used whatever template was attached to the documentation here

 

GitHub - microsoft/dicom-server: OSS Implementation of DICOMweb standard <https://github.com/microsoft/dicom-server> 

Deploy to Azure

If you already have an Azure subscription, deploy the Medical Imaging Server for DICOM directly to Azure:
 <https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2Fdicom-server%2Fmain%2Fsamples%2Ftemplates%2Fdefault-azuredeploy.json> 

 

I also assigned false to that environment variable. Do I have to do anything else to make it active?

 

Thanks again

 

Dave Collins

**Comment by wsugarman** [comment]
You shouldn't need to take any additional action if you used our default ARM template, like you linked. `false` should be the default value for `DicomServer__Security__Enabled`, but being explicit shouldn't have an adverse effect. If you wish to ever enable security, you can review our docs on both [authentication](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/enable-authentication-with-tokens.md) and [authorization](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/enable-authorization.md).

**Comment by dwcollins** [comment]
Thanks Will

 

Dave Collins
