### ISSUE TITLE
Enable authorization procedure not working

### ISSUE THREAD

**Issue by sihbher** [microsoft/dicom-server#1914]
I am trying to follow [Enable authorization](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/enable-authorization.md) step by step, it shows how to create:

1. Create a Resource Application in Azure AD for your Medical Imaging Server for DICOM
2. Create a Service Client Application

But some steps seem confusing:

A. In the section "Get Access Token Using Azure CLI":

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/59939147/188518957-0b916efe-62d0-408e-9000-d09144f3ca6d.png">
It is not clear to me to which app registration you refer to, I guess is the second one, if so, for me is greyed out: 

![image](https://user-images.githubusercontent.com/59939147/188519725-a88d7363-0749-45ec-9f76-aa07d3b1c2bc.png)

B. In the section "Get Access Token Using Postman"
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/59939147/188519180-2fa3063b-c7c2-4d9d-a987-acaa7b5ea67b.png">

I guess it refers to the second app registration again, and It says that you have to use as **resource** the application ID Uri of the app registration which has a format like api://{ClientID}/.default, but if I use that application ID Uri Postman gives me an error:

![image](https://user-images.githubusercontent.com/59939147/188519439-97c9faba-bafe-4027-87d9-a62ec14f79d9.png)

But if I use "https://dicom.healthcareapis.azure.com" as resource it works:
![image](https://user-images.githubusercontent.com/59939147/188519539-33922407-4a6d-4b9a-af80-3b2de4b39ef2.png)

So, what am I doing wrong following the tutorial?

**Comment by brandonpollett** [comment]
It looks like in a, there is no scope exposed as pointed out in step 4 of https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/enable-authentication-with-tokens.md#create-a-resource-application-in-azure-ad-for-your-medical-imaging-server-for-dicom

For b, this is likely related, so I would make sure you have a scope exposed as a first step.

**Comment by smithago** [comment]
closing as stale
