### ISSUE TITLE
Support WADO-RS - Retrieve Rendered Transaction

### ISSUE THREAD

**Issue by AbrahamBhererConstantElekta** [microsoft/dicom-server#2051]
**User story**
As a user of DICOMweb, I want to use the [retrieve rendered transactions][1] so that I can take advantage of the [image quality parameter][2] to enable more responsive visualization of the server content.

Currently, visualizing large series requires the download of the full files, which can be slow.

**Acceptance criteria**
1. When I use the `{s}/studies/{study}/series/{series}/instances/{instance}/rendered` route, then I receive rendered and optionnally compressed images instead of full DICOM objects.

[1]: https://dicom.nema.org/medical/dicom/2016b/output/chtml/part18/sect_6.5.8.html
[2]: https://dicom.nema.org/medical/dicom/2016b/output/chtml/part18/sect_6.5.8.html#sect_6.5.8.1.2.2

**Comment by mmitrik** [comment]
@abrahambhererconstant-elekta - thanks for submitting the feature request ✨ 

We are beginning work on the `/rendered` endpoint, and I was curious about your thoughts on a few things:

1. Is support for Instance and Frame resources sufficient for your use cases?  Do you need rendered support for Series and Study resources?
2. Regarding image types, will jpeg and png meet your needs?
3. Do you care at all about Thumbnail resources?  Most customers have asked about the rendered endpoint specifically, and I'm not aware of any needing thumbnail resources (despite preview images being a common use case).
4. You mention the image quality param specifically - would the feature be useful to you without support for that parameter?  

Thanks in advance for any insights you can provide!

cc @bcarthic @abdullah248

**Comment by abrahambhererconstant-elekta** [comment]
1. Support for Instance and Frame resources is the most important. This would allow quick generation to get preview images to a client. 
  
   For Series resources, an endpoint that allows fetching Dicom objects with compressed jpg image data would be useful to minimize file size, but I believe this is out of the scope of WADO. WADO seems to support `image/gif` for multi-image series which would not be useful to us.

2. Yes
3. I do not know what "Thumbnail resources" are in this context. Would you mind elaborating?
4. This endpoint's main benefit is reducing the file size of images for quick preview. The `quality` param is not required if the default jpg compression level reduces the file size significantly

**Comment by mmitrik** [comment]
Thanks for the reply, @abrahambhererconstant-elekta ✨ 

Re: Thumbnail resources - this is a similar resource defined in the DICOM standard, but it does not seem to be commonly supported.  We don't have customers asking for it, but I was curious if you were in need of it.  Details about [thumbnails](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.4.1.1.4).

**Comment by abrahambhererconstant-elekta** [comment]
We would have no additional use case for the thumbnails endpoint over the rendered endpoint.

I learned something new about dicom, thank you!

**Comment by abdullah248** [comment]
Hi @AbrahamBhererConstantElekta,  we now have support for the rendered endpoint to retrieve rendered instances and frames in the PNG and JPEG format. For the JPEG format the quality can be specified using the query paramater. 

Our conformance statement has been updated as well with more details: https://github.com/microsoft/dicom-server/blob/main/docs/resources/conformance-statement.md#retrieve-rendered-image-for-instance-or-frame

Please let us know if you have any feedback. 
Thanks!
