### ISSUE TITLE
Online index operations can only be performed in Enterprise edition of SQL Server.

### ISSUE THREAD

**Issue by ashutosh1211** [microsoft/dicom-server#2273]
Getting following error on starting the server.

Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
Online index operations can only be performed in Enterprise edition of SQL Server.
   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
ClientConnectionId:8f94daa7-635a-47d7-a63d-0d680f615cc4
Error Number:1712,State:1,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand)
   at Microsoft.Health.SqlServer.Features.Schema.Manager.SchemaManagerDataStore.ExecuteScriptAsync(String script, CancellationToken cancellationToken)
   at Microsoft.Health.SqlServer.Features.Schema.SchemaUpgradeRunner.ApplySchemaAsync(Int32 version, Boolean applyFullSchemaSnapshot, CancellationToken cancellationToken)

**Comment by smithago** [comment]
Hello, you will need Enterprise SQL to run the upgrade scripts.
