### ISSUE TITLE
Add support for callbacks in the export API

### ISSUE THREAD

**Issue by daker** [microsoft/dicom-server#2629]
**User story**
As a developer, I want to be notified at the end of the export operation so that i can execute a function, ex: send mail notification.

**Acceptance criteria**
1. When I do call the export api, then the provided callback is triggered by dicom-server at the end of the operation.

```json
{
  "source": {
    "type": "unknown"
  },
  "destination": {
    "type": "unknown"
  },
 "callback": "https://example.com/mycallback"
}
```

**Comment by wsugarman** [comment]
@daker Thanks for the suggestion! I can understand that a push-based model would be convenient for long-running operations like our re-indexing and export operation. However, we're reluctant to add arbitrary callbacks from the DICOM server to any endpoint. That being said, we do have some plans to make it much easier to interact with DCM files from within an Azure Storage account. Are you by chance a user of our OSS project or in the [Azure Health Data Services](https://azure.microsoft.com/en-us/products/health-data-services/)?

**Comment by daker** [comment]
We are using the SaaS version in Azure(Azure Health Data Services)

**Comment by daker** [comment]
@wsugarman do you have an idea when those plans are going to be shared?

**Comment by wsugarman** [comment]
We do not yet have a date, but feel free to keep an eye out in this repository for changes related to the usage of blob storage. We'll also update here and through official channels with more news in the future.
