### ISSUE TITLE
Azure DevOps error when restoring Microsoft.Health.Dicom.Client

### ISSUE THREAD

**Issue by koswedo** [microsoft/dicom-server#2886]
**Describe the bug**
When building using Visual Studio, I can add `Microsoft.Health.Dicom.Client` as a dependency and build my solution.
Build pipeline in Azure DevOps worked fine till July 6th. From this date on, We get a lot of errors that look like this:
```
Retrying 'FindPackagesByIdAsync' for source 'https://microsofthealthoss.pkgs.visualstudio.com/7621b231-1a7d-4364-935b-2f72b911c43d/_packaging/a60b7c8b-c6ae-4a8e-bd15-a526b603a1f2/nuget/v3/flat2/mediatr.extensions.microsoft.dependencyinjection/index.json'.
Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'mediatr.extensions.microsoft.dependencyinjection'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: E5E44E9D-EC8B-4D9D-8C42-EA51C1E2F4FE)).
```

our nuget.config file hasn't changed
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear />
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json"/>
        <add key="Public" value="https://microsofthealthoss.pkgs.visualstudio.com/FhirServer/_packaging/Public/nuget/v3/index.json" />
    </packageSources>
</configuration>
```

Another developer seems to have the same issue: https://stackoverflow.com/questions/76640185/azure-devops-response-status-code-does-not-indicate-success-401-unauthorized

**To Reproduce**
1. Create a project that references `Microsoft.Health.Dicom.Client`. 
2. Create an Azure DevOps pipeline
3. Run the pipeline
It fails when trying to restore dependencies

**Expected behavior**
It should restore dependencies without errors

**Actual behavior**
It does not restore dependencies and throw errors

**Comment by EugeneBogushevich** [comment]
Yes, confirming the same issue happened to us. I posted my comment in above mentioned SO link: https://stackoverflow.com/a/76662452

**Note:** 
if you use their CI feed, seems it works fine: https://microsofthealthoss.visualstudio.com/FhirServer/_artifacts/feed/CI/connect/nuget.exe

`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="CI" value="https://microsofthealthoss.pkgs.visualstudio.com/FhirServer/_packaging/CI/nuget/v3/index.json" />
  </packageSources>
</configuration>
`

**Comment by brandonpollett** [comment]
Thanks for the heads up. We'll check to see if anything changed with the feed configuration.

**Comment by haywoodIII** [comment]
Any update on this? Running into this issue as well and the package, "Microsoft.Health.Dicom.Client," no longer is in the CI feed?

**Comment by wsugarman** [comment]
@haywoodIII - Are you still encountering this problem? I was able to successfully perform a `dotnet restore` after referencing the package `Microsoft.Health.Dicom.Client` via the `Public` feed in a new dev environment. But perhaps I unintentionally included some additional authentication.

**Comment by wsugarman** [comment]
I'm going to close the issue for now pending other users that may report issues
