### ISSUE TITLE
 Current SQL schema version could not be resolved.

### ISSUE THREAD

**Issue by ashutosh1211** [microsoft/dicom-server#2967]
Getting following error with latest code.

`info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]       Executed action Microsoft.Health.Dicom.Api.Controllers.QueryController.QueryForStudyAsync (Microsoft.Health.Dicom.Api) in 753.3386ms warn: Microsoft.Health.Dicom.Api.Features.Exceptions.ExceptionHandlingMiddleware[0]       Service exception.       Microsoft.Health.Dicom.Core.Exceptions.DataStoreNotReadyException: Current SQL schema version could not be resolved.          at Microsoft.Health.Dicom.SqlServer.Features.Schema.VersionedCache1.ResolveAsync(CancellationToken cancellationToken) `

**Comment by jnlycklama** [comment]
Are you updating an existing service? If so, what schema version was previously referenced?
Or are you creating a new service?

**Comment by ashutosh1211** [comment]
I am running it as a new service, no database exists, so when I run the project it creates db but in further steps it fails.

**Comment by ashutosh1211** [comment]
Im currently running it locally in dev environment. 

tables are not getting created on initial run, only database is created. 

some lines from logs.

```
warn: Microsoft.Health.SqlServer.Features.Schema.SchemaInitializer[0]
      Could not find stored procedure - dbo.SelectCurrentSchemaVersion
info: Microsoft.Health.SqlServer.Features.Schema.SchemaInitializer[0]
      Initial check of schema version is NULL
...
...
...
info: Microsoft.Health.Dicom.Core.Features.Partition.PartitionCache[0]
      Cache miss. Initializing the row.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
      Executed action Microsoft.Health.Dicom.Api.Controllers.QueryController.QueryForStudyAsync (Microsoft.Health.Dicom.Api) in 931.399ms
warn: Microsoft.Health.Dicom.Api.Features.Exceptions.ExceptionHandlingMiddleware[0]
      Service exception.
      Microsoft.Health.Dicom.Core.Exceptions.DataStoreNotReadyException: Current SQL schema version could not be resolved.
         at Microsoft.Health.Dicom.SqlServer.Features.Schema.VersionedCache`1.ResolveAsync(CancellationToken cancellationToken) in 
```

**Comment by ashutosh1211** [comment]
may be default stored procedures are not getting created from shared health package and Initial check of schema version is NULL error is coming.

**Comment by jnlycklama** [comment]
Have you been through these instructions if you are running the service locally? https://github.com/microsoft/dicom-server/blob/main/docs/development/setup.md

**Comment by ashutosh1211** [comment]
> Have you been through these instructions if you are running the service locally? https://github.com/microsoft/dicom-server/blob/main/docs/development/setup.md
> 

Yes, I'm following the guidelines.

**Comment by ashutosh1211** [comment]
I have resolved the issue by following steps in SqlServer readme.md file. We can close this issue.
