### ISSUE TITLE
Container Status Remaining "Waiting" While Deploying DICOMCast

### ISSUE THREAD

**Issue by HitakshiDobariya99** [microsoft/dicom-server#3076]
I've deployed [DICOM Cast](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-dicom-cast.md#deploy-via-azure-with-oss) successfully. And performed all the steps of [Sync Medical Imaging Server for DICOM metadata into FHIR Server for Azure](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md). But unable to get the corresponding FHIR resources in FHIR service.

**Here is the detailed container log:**
```
info: Microsoft.Health.DicomCast.TableStorage.Features.Storage.TableServiceClientInitializer[0]
      Created Table named 'TransientRetryExceptionTable'
info: Microsoft.Health.DicomCast.TableStorage.Features.Storage.TableServiceClientInitializer[0]
      Table Storage and tables successfully initialized
info: Azure.Identity[1]
      DefaultAzureCredential.GetToken invoked. Scopes: [ https://dc2healthdataservice-dc2fhirservice.fhir.azurehealthcareapis.com ] ParentRequestId: 
info: Azure.Identity[1]
      EnvironmentCredential.GetToken invoked. Scopes: [ https://dc2healthdataservice-dc2fhirservice.fhir.azurehealthcareapis.com ] ParentRequestId: 
info: Azure.Identity[3]
      EnvironmentCredential.GetToken was unable to retrieve an access token. Scopes: [ https://dc2healthdataservice-dc2fhirservice.fhir.azurehealthcareapis.com ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
info: Azure.Identity[1]
      WorkloadIdentityCredential.GetToken invoked. Scopes: [ https://dc2healthdataservice-dc2fhirservice.fhir.azurehealthcareapis.com ] ParentRequestId: 
info: Azure.Identity[3]
      WorkloadIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://dc2healthdataservice-dc2fhirservice.fhir.azurehealthcareapis.com ] ParentRequestId:  Exception: Azure.Identity.
 (0x80131500): WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/workloadidentitycredential/troubleshoot
info: Azure.Identity[1]
      ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dc2healthdataservice-dc2fhirservice.fhir.azurehealthcareapis.com ] ParentRequestId: 
```

To resolve this issue I've set environmental variables such as AZURE_CLIENT_ID, AZURE_TENANT_ID, and AZURE_CLIENT_SECRET while [deployment via Azure with OSS](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-dicom-cast.md#deploy-via-azure-with-oss).

After successfully setting the environment variables, The container state remains **"waiting"**.

**Comment by jnlycklama** [comment]
`DefaultAzureCredential` will go through different types of authentication until it finds one that works - https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication/?tabs=command-line#exploring-the-sequence-of-defaultazurecredential-authentication-methods
So its not failing on `EnvironmentCredential` or `WorkloadIdentityCredential`, but just moving on to the next credential. It looks like it finally uses `ManagedIdentityCredential` and stops there. 

https://github.com/microsoft/dicom-server/blob/main/converter/dicom-cast/docs/authentication.md - see these docs for more options on how to set up authentication

**Comment by HitakshiDobariya99** [comment]
Thank you for your reply, 

As you describe here, `DefaultAzureCredential`  uses `ManagedIdentityCredential`

As per the [documentation ](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md)I've followed all the steps and still facing this [error](https://github.com/microsoft/dicom-server/issues/3045).

**Comment by HitakshiDobariya99** [comment]
We are still facing issues with the sample application implementations.

Followed the [documentation](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md), I've followed all the steps and still facing this https://github.com/microsoft/dicom-server/issues/3045.

Is there any other way or possibility that you can help ?

**Comment by HitakshiDobariya99** [comment]
Hello @jnlycklama 

We are still facing issues with the sample application implementations.

Followed the [documentation](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md), I've followed all the steps and still facing this https://github.com/microsoft/dicom-server/issues/3045.

Is there any other way or possibility that you can help ?
