### ISSUE TITLE
Getting an Error While Deploying Dicomcast via Azure With Azure Heathcare APIs

### ISSUE THREAD

**Issue by HitakshiDobariya99** [microsoft/dicom-server#3142]
I'm Deploying DicomCast via [Azure with Azure healthcare APIs](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-dicom-cast.md#deploy-via-azure-with-azure-healthcare-apis), Getting an error: 
```
{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The value for the template parameter 'imageTag' at line '20' and column '21' is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.'."
}
```
In the below screenshot, you can able to see that I've provided value to ImageTag.
![Screenshot 2023-10-26 231523](https://github.com/microsoft/dicom-server/assets/101874176/b7504fc3-7b12-48c7-a13b-1c9086926e73)

**Comment by poadhika** [comment]
This issue will be resolved by this PR. https://github.com/microsoft/dicom-server/pull/3148

**Comment by arunmk-ms** [comment]
Hi @HitakshiDobariya99 , the issue has been fixed. Please use the updated template and let us know if you are still facing the issue.

**Comment by HitakshiDobariya99** [comment]
Hello @arunmk-ms 

Now Getting this error while deploying with [updated ARM template](https://github.com/microsoft/dicom-server/pull/3148/commits/20e0eeeda47ee9022ff4bcdd9aec58587bc867b3) and the deployment link provide [here](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-dicom-cast.md#deploy-via-azure-with-azure-healthcare-apis):
![image](https://github.com/microsoft/dicom-server/assets/101874176/0ed71945-eba4-40a5-80fa-34bc37c7d684)

**Comment by arunmk-ms** [comment]
Hi @HitakshiDobariya99 please use the [updated template](https://github.com/microsoft/dicom-server/blob/main/converter/dicom-cast/samples/templates/deploy-with-healthcareapis.json) and let us know if you are still facing the issue.

**Comment by HitakshiDobariya99** [comment]
Hi @arunmk-ms, 
Thank you. It is working now.
