### ISSUE TITLE
406 Unaccepted error with latest ohif viewer 

### ISSUE THREAD

**Issue by harmydiano** [microsoft/dicom-server#3287]
**Describe the bug**
Series metadata fails to load when using the latest ohif viewer. It throws a 406 Unaccepted error.

`https://example.cloudapp.azure.com/v1/studies/1.3.6.1.4.1.34656.2.30.90.22.677.202312221549188972/series
Request Method:
GET
Status Code:
406 Not Acceptable`

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**
An older version of ohif works very well with the server. It loads the studies and it's metadata

**Actual behavior**
The ohif viewer fails to load the metadata from the series endpoint. It throws a 406 Unaccepted error message.

**Comment by bcarthic** [comment]
@harmydiano The uploaded image is not visible to us. Could you check what error message does the OHIF viewer throws, you can check using F12 Developer Tools. When you say older version, what is the version you were using earlier?

**Comment by harmydiano** [comment]
@bcarthic you can recheck the image

**Comment by bcarthic** [comment]
@harmydiano Sure, my question was what error you see from developer tools? The developer tools outputs the exact message on why it is failing. May be OHIF viewer sends a different header that is not accepted. And we haven't changed the viewer for a quite a long time. New viewer is just merged 2 days back.

**Comment by harmydiano** [comment]
Hi @bcarthic, the error displayed in the developer tools is `GET Status Code: 406 Not Acceptable`

**Comment by bcarthic** [comment]
@harmydiano, you can see the detailed messaged in the preview or response tab

**Comment by harmydiano** [comment]
@bcarthic , You can have a look at it here https://xcel-solutions-ingress.eastus.cloudapp.azure.com/ohif/viewer?StudyInstanceUIDs=1.2.840.113619.2.428.3.2831160320.847.1696250782.351

**Comment by harmydiano** [comment]
<img width="1273" alt="Screenshot 2024-01-18 at 21 54 28" src="https://github.com/microsoft/dicom-server/assets/35279622/1ccffac1-7156-4c2b-8bc1-2343b436fd90">

**Comment by harmydiano** [comment]
The preview and response tab is empty

**Comment by bcarthic** [comment]
@harmydiano thanks for the url and the screenshot. We have fixed an issue and merged the fix yesterday. Please try to update your build and let me know if that works. Also, could you query your application insights logs and let me know the exception and stacktrace?

**Comment by harmydiano** [comment]
Hi @bcarthic, I ran the docker build setup using this command `docker build -f src/Microsoft.Health.Dicom.Web/Dockerfile -t dicom-server .`

and i got the following error

` => ERROR [build 6/6] RUN dotnet build "Microsoft.Health.Dicom.Web.csproj" -c Release -p:ContinuousIntegrationBuild=false -warnaserror                                      452.2s
------                                                                                                                                                                              > [build 6/6] RUN dotnet build "Microsoft.Health.Dicom.Web.csproj" -c Release -p:ContinuousIntegrationBuild=false -warnaserror:                                                   
#0 1.689 MSBuild version 17.8.3+195e7f5a3 for .NET                                                                                                                                 #0 3.077   Determining projects to restore...                                                                                                                                      
#0 26.83   Restored /dicom-server/src/Microsoft.Health.Dicom.WebUtilities/Microsoft.Health.Dicom.WebUtilities.csproj (in 19.49 sec).                                               #0 38.41   Restored /dicom-server/src/Microsoft.Health.Dicom.Functions.Abstractions/Microsoft.Health.Dicom.Functions.Abstractions.csproj (in 30.56 sec).                           
#0 50.83   Restored /dicom-server/src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj (in 23.86 sec).
#0 52.58   Restored /dicom-server/src/Microsoft.Health.Dicom.Functions.Client/Microsoft.Health.Dicom.Functions.Client.csproj (in 1.22 sec).
#0 54.87   Restored /dicom-server/src/Microsoft.Health.Dicom.Core/Microsoft.Health.Dicom.Core.csproj (in 1.97 sec).
#0 54.97   Restored /dicom-server/src/Microsoft.Health.Dicom.Blob/Microsoft.Health.Dicom.Blob.csproj (in 19 ms).
#0 54.99   Restored /dicom-server/src/Microsoft.Health.Dicom.Azure/Microsoft.Health.Dicom.Azure.csproj (in 13 ms).
#0 55.18   Restored /dicom-server/src/Microsoft.Health.Dicom.SqlServer/Microsoft.Health.Dicom.SqlServer.csproj (in 16.74 sec).
#0 55.24   Restored /dicom-server/src/Microsoft.Health.Dicom.Api/Microsoft.Health.Dicom.Api.csproj (in 212 ms).
#0 56.54   Restored /dicom-server/forks/Microsoft.Health.FellowOakDicom/Microsoft.Health.FellowOakDicom.csproj (in 1.36 sec).
#0 65.45   Microsoft.Health.FellowOakDicom -> /dicom-server/forks/Microsoft.Health.FellowOakDicom/bin/Release/net8.0/Microsoft.Health.FellowOakDicom.dll
#0 83.35   Microsoft.Health.Dicom.Core -> /dicom-server/src/Microsoft.Health.Dicom.Core/bin/Release/net8.0/Microsoft.Health.Dicom.Core.dll
#0 439.2   Microsoft.Health.Dicom.SqlServer -> /dicom-server/src/Microsoft.Health.Dicom.SqlServer/bin/Release/net8.0/Microsoft.Health.Dicom.SqlServer.dll
#0 439.6   Microsoft.Health.Dicom.Azure -> /dicom-server/src/Microsoft.Health.Dicom.Azure/bin/Release/net8.0/Microsoft.Health.Dicom.Azure.dll
#0 441.1   Microsoft.Health.Dicom.Blob -> /dicom-server/src/Microsoft.Health.Dicom.Blob/bin/Release/net8.0/Microsoft.Health.Dicom.Blob.dll
#0 441.3   Microsoft.Health.Dicom.WebUtilities -> /dicom-server/src/Microsoft.Health.Dicom.WebUtilities/bin/Release/net8.0/Microsoft.Health.Dicom.WebUtilities.dll
#0 442.0   Microsoft.Health.Dicom.Functions.Abstractions -> /dicom-server/src/Microsoft.Health.Dicom.Functions.Abstractions/bin/Release/net8.0/Microsoft.Health.Dicom.Functions.Abstractions.dll
#0 442.7   Microsoft.Health.Dicom.Functions.Client -> /dicom-server/src/Microsoft.Health.Dicom.Functions.Client/bin/Release/net8.0/Microsoft.Health.Dicom.Functions.Client.dll
#0 445.8   Microsoft.Health.Dicom.Api -> /dicom-server/src/Microsoft.Health.Dicom.Api/bin/Release/net8.0/Microsoft.Health.Dicom.Api.dll
#0 449.9   Microsoft.Health.Dicom.Web -> /dicom-server/src/Microsoft.Health.Dicom.Web/bin/Release/net8.0/Microsoft.Health.Dicom.Web.dll
#0 451.1   Skipping NuGet package signature verification.
#0 451.3   Tool 'swashbuckle.aspnetcore.cli' (version '6.5.0') was restored. Available commands: swagger
#0 451.3   
#0 451.3   Restore was successful.
#0 451.8   You must install or update .NET to run this application.
#0 451.8   
#0 451.8   App: /root/.nuget/packages/swashbuckle.aspnetcore.cli/6.5.0/tools/net7.0/any/dotnet-swagger.dll
#0 451.8   Architecture: x64
#0 451.8   Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
#0 451.8   .NET location: /usr/share/dotnet/
#0 451.8   
#0 451.8   The following frameworks were found:
#0 451.8     6.0.26 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
#0 451.8     8.0.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
#0 451.8   
#0 451.8   Learn more:
#0 451.8   https://aka.ms/dotnet/app-launch-failed
#0 451.8   
#0 451.8   To install missing framework, download:
#0 451.8   https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=linux-musl-x64&os=alpine.3.18
#0 451.8 /dicom-server/src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj(42,5): error MSB3073: The command "dotnet swagger tofile  --yaml --output ..\..\swagger\v1\swagger.yaml bin/Release/net8.0/\Microsoft.Health.Dicom.Web.dll v1" exited with code 150.
#0 451.8 
#0 451.8 Build FAILED.
#0 451.8 
#0 451.8 /dicom-server/src/Microsoft.Health.Dicom.Web/Microsoft.Health.Dicom.Web.csproj(42,5): error MSB3073: The command "dotnet swagger tofile  --yaml --output ..\..\swagger\v1\swagger.yaml bin/Release/net8.0/\Microsoft.Health.Dicom.Web.dll v1" exited with code 150.
#0 451.8     0 Warning(s)
#0 451.8     1 Error(s)
#0 451.8 
#0 451.8 Time Elapsed 00:07:29.87
------
Dockerfile:31
--------------------
  29 |     COPY . .
  30 |     WORKDIR /dicom-server/src/Microsoft.Health.Dicom.Web
  31 | >>> RUN dotnet build "Microsoft.Health.Dicom.Web.csproj" -c $BUILD_CONFIGURATION -p:ContinuousIntegrationBuild=$CONTINUOUS_INTEGRATION_BUILD -warnaserror
  32 |     
  33 |     # Publish the DICOM Server from the build
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet build \"Microsoft.Health.Dicom.Web.csproj\" -c $BUILD_CONFIGURATION -p:ContinuousIntegrationBuild=$CONTINUOUS_INTEGRATION_BUILD -warnaserror" did not complete successfully: exit code: 1`

**Comment by bcarthic** [comment]
@harmydiano you could set the ARG CONTINUOUS_INTEGRATION_BUILD to true in the dockerfile for a temporary workaround. It fails on generating the swagger files, which is not required in this case

**Comment by bcarthic** [comment]
Closing this issue as there are no response
