### ISSUE TITLE
Download study as a zip file of dcm files.

### ISSUE THREAD

**Issue by ashutosh1211** [microsoft/dicom-server#3358]
**User story**
As a user, I want to download all the raw dicom files so that i can view them in my local dicom viewer workstation.

**Acceptance criteria**
1. API which will take study id as input and generate zip file to download.

**Comment by arunmk-ms** [comment]
Hi @ashutosh1211, have you looked into our export feature [here](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/export-data.md)?

**Comment by ashutosh1211** [comment]
Yes, but it works on blob to blob export, I need to export it as a zip file.

**Comment by arunmk-ms** [comment]
The bulk export API takes a study ID as input, according to your specifications. It then retrieves all the corresponding blobs and stores them in a designated storage account. However, please note that our current feature set does not include the ability to download the blob as a zip file.

**Comment by ashutosh1211** [comment]
Its common requiment of radiologists where they want to view these DICOM files on their preferred workstation.

**Comment by arunmk-ms** [comment]
Each study instance can have a maximum size of up to 4 GB. It is not recommended to download multiple instances in a single API response, as doing so could unnecessarily burden your application server. Instead, consider using the [metadata](https://github.com/microsoft/dicom-server/blob/main/docs/resources/conformance-statement.md#:~:text=within%20a%20study.-,GET,Retrieves%20the%20metadata%20for%20all%20instances%20within%20a%20study.,-GET) API to retrieve individual study instance UIDs and then use the WADO API for each of them separately.
