### ISSUE TITLE
DICOM Cast URL not working

### ISSUE THREAD

**Issue by cyberuna** [microsoft/dicom-server#361]
In this URL: https://github.com/microsoft/dicom-server/blob/master/docs/quickstarts/deploy-dicom-cast.md, this URL for DICOM Cast Concept doesn't work: https://github.com/microsoft/dicom-server/blob/master/docs/docs/concepts/dicom-cast.md

**Comment by moiradillon12** [comment]
Addressing this in : https://github.com/microsoft/dicom-server/pull/365

**Comment by StevenBorg** [comment]
Thanks, @cyberuna for the bug report!  We really appreciate it!
