### ISSUE TITLE
Sample ARM template uses a deploy package from CI output instead of a versioned artifact

### ISSUE THREAD

**Issue by sven-hoffmann** [microsoft/dicom-server#407]
**Describe the bug**
The provided sample ARM template to deploy the DICOMweb server is currently using a URL for the deployment package which is not versioned and seems to be the output of the build result of the "master" branch pipeline.

File location: 
https://github.com/microsoft/dicom-server/blob/master/samples/templates/default-azuredeploy.json

(Current) line number: 180

Content:
"defaultDeployPackageUrl": "https://dcmcistorage.blob.core.windows.net/cibuild/Microsoft.Health.Dicom.Web.zip",

If you do not want to build the project from source this make the DICOMweb server currently an unpinned dependency (essentialy a "snapshot" or "latest" type dependency). This means that we can not be sure what will be the content of our deployments depending on this product at any time, revert back or update in a controlled manner.

**To Reproduce**
1. Deploy using ARM template
2. Wait for DICOMweb server master pipeline to run or run it manually
3. Deployment contents of DICOMweb server will now change if you deploy again

**Expected behavior**
- I expect a versioned deploy package to be available under a well known URL. (Github artifact would be my preference, other options: Azure DevOps artifact, blob storage would be ok too).

Examples for current latest tag; Microsoft.Health.Dicom.Web-1.0.0-master-20201015-1.zip

Also expected behavior: The content of zip file is immutable - will never change again.

**Actual behavior**
- The content of https://dcmcistorage.blob.core.windows.net/cibuild/Microsoft.Health.Dicom.Web.zip changes with every build of the ci pipeline run for the DICOMweb server

**Comment by StevenBorg** [comment]
@sven-hoffmann, I apologize for the delay. We're working on a solution now, and will have it out to you shortly.  Thanks for your patience, and thank you so much for reporting the issue so clearly. Although the current plan is for the ARM template to deploy the latest by default, we will create immutable releases as well as documentation for how to update the ARM teamplte to reference those releases.

**Comment by sven-hoffmann** [comment]
Hi @StevenBorg 
is there any update on the immutable releases? We just had exactly the issue where we saw the risk. 
The new deployment package apparently provided at Tue, 09 Feb 2021 01:18:53 GMT according to the Last-Modified header does no longer work for us and blocks our pipeline and integrating products. We're currently trying to find a solution but long story short. This is still a topic that should be adressed in my opinion.

**Comment by smithago** [comment]
close as stale
