### ISSUE TITLE
OHIF Azure Active Directory

### ISSUE THREAD

**Issue by casey-spires** [microsoft/dicom-server#424]
I've setup the dicom-server with azure active directory to authenticate requests but... I haven't found any documentation on how to configure OHIF to authenticate with azure active directory. I know this is more of an issue with OHIF, but it's a key piece to getting this up and running with my org. This is my current config. 

                oidc: [
                {
                  // ~ REQUIRED
                  // Authorization Server URL
                  authority: 'https://login.microsoftonline.com/<tenant>',
                  client_id: '<clientId,
                  redirect_uri: 'https://<site>.azurewebsites.net',
                  response_type: 'code', // "Authorization Code Flow"
                  scope: 'openid profile <custom scope>', // email profile openid
                  // ~ OPTIONAL
                  automaticSilentRenew: true,
                }
              ]

**Comment by casey-spires** [comment]
I just wanted to follow up on how i solved this issue. When deploying to the web application service rather than enabling Azure AD Authentication at the application level, I enabled it at the Web App Service Level with an Advanced Configuration, setting token audiences that are allowed to access the resource. This protects the OHIF View and the Dicom Server While Allowing for REST Operations from external Applications. If you need more explanation please reach out to me.

**Comment by StevenBorg** [comment]
Thank you so much for the issue, Casey! Currently, the OHIF viewer is added to the server for initial testing. It's not meant to be used in production, but many initial users wanted to be able to visually verify when they had data uploaded.  We currently do not support Azure AD authentication with the OHIF viewer.  However, that is not clear in either the documentation, and no warning is given.  

Our first approach will be to update the documentation reflecting our lack of support for OHIF on an AAD enabled site. Following that, we'll look into potential options to enable OHIF support for AAD enabled sites, which may include recommendations for setting up a separate OHIF website, secured with AAD, that interacts with the Medical Imaging Server for DICOM.

Casey, will those approaches work for you?  If you'd like to contact me directly, feel free to reach out to me on LinkedIn (a simple search should find me), and we can talk in more depth.

Once again, thank you so much for taking the time to submit the issue.  I appreciate it.

**Comment by StevenBorg** [comment]
Looping in @brandonpollett for more information.

**Comment by mschmieder** [comment]
I just stumbled over this issue and wanted to point you to some more details about OHIF <-> OIDC <-> AAD. We have been lately trying to setup the system and have collected some information which resulted in a MR. Please see the already merged pull request on the OHIF side. 

https://github.com/OHIF/Viewers/pull/2167

There are still some issues with CORS when using AAD, but by providing the necessary metadata it was possible to successfully setup Authentication.

**Comment by StevenBorg** [comment]
Thank you @mschmieder!  This is great news!  I'm re-looping in @moiradillon12 and @brandonpollett again for next steps!

**Comment by StevenBorg** [comment]
@mschmieder, thank you so much for this Issue.  We've taken a look at the potential solution and it's going to take some effort. Although we love that OHIF makes creating a compelling demo environment easy, a production service likely wouldn't include that as a front end. Because of the effort involved and the lack of production use, we're going to close this Issue for now.  However, if we do further work around OHIF, we will add support at that time.  Sorry, Matthais.  We'd love to support it. But we're so focused on other items we're not going to attack it now.  

That said, if you have ideas and/or code, I'd love to hear them or take a pull request.  :-)
