### ISSUE TITLE
Publish the DicomWebClient package in Nuget

### ISSUE THREAD

**Issue by andreracz** [microsoft/dicom-server#432]
**User story**
As a DICOM Developer, I want to be able do use the DicomWebClient library to access the server so that I don't have to write the code for that.

**Acceptance criteria**
1. When I do dotnet package add Microsoft.Health.Dicom.Client, then the package is downloaded.

**Comment by StevenBorg** [comment]
Andre, thank you so much for your issue.  Looping in @brandonpollett.

**Comment by smithago** [comment]
Thanks for the input. Right now the web client is published to a internal feed. To workaround you can build the project or download it from the latest CI published artifacts.
