### ISSUE TITLE
Deploying DICOM Cast without AppInsights fails

### ISSUE THREAD

**Issue by andreracz** [microsoft/dicom-server#433]
**Describe the bug**
When using the parameter to not create app insights, when deploying DICOM-Cast, the deployement fails

**To Reproduce**
1.  Try to deploy DICOM Cast thru ARM
2.  Set the parameter for Create App Insights to false.

**Expected behavior**
The solution is deployed.

**Actual behavior**
Deployment fails with error:

{
  "deploymentStatusCode": -1,
  "stage": 6,
  "expected": true,
  "error": {
    "message": "Deployment template validation failed: 'The template resource 'Microsoft.ContainerInstance/containerGroups/dicom-cast-xxxxxx' reference to 'Microsoft.Insights/components/AppInsights-dicom-cast-xxxxxx' requires an API version. Please see https://aka.ms/arm-template for usage details.'."
  },
  "subscriptionId": "xxxxxxxxxxxxxxxx",
  "resourceGroupName": "dicom-cast",
  "resourceGroupLocation": "eastus",
  "deploymentName": "Microsoft.Template-20201113162042",
  "details": {
    "code": "InvalidTemplate",
    "message": "Deployment template validation failed: 'The template resource 'Microsoft.ContainerInstance/containerGroups/dicom-cast-xxxxxx' reference to 'Microsoft.Insights/components/AppInsights-dicom-cast-xxxxxx' requires an API version. Please see https://aka.ms/arm-template for usage details.'.",
    "additionalInfo": [
      {
        "type": "TemplateViolation",
        "info": {
          "lineNumber": 0,
          "linePosition": 0,
          "path": ""
        }
      }
    ]
  }
}

**Comment by StevenBorg** [comment]
Thanks so much for your issue submission, @andreracz !  We very much appreciate it, and are looking into it now. Quick question, we've considered making App Insights mandatory, since it helps running the system in production. But it does cost, and isn't part of the core functionality. We obviously will fix this issue, but I'm curious as to the context in which you'd spin up a service without wanting App Insights. Would you be open to a brief conversation?  Either in this Issue, or via Teams?

**Comment by andreracz** [comment]
I was just creating a test server for seeing how DICOM Cast worked, in order to reduce the cost and speed up the test. Since it had the option, I just flagged it. I love App Insights and would never use it in production without it, but I have seen some scenarios where customers prefer to use other solutions, such as DataDog, so this could be a scenario.

If you want to setup a teams meeting to further discuss this, no problem.

**Comment by StevenBorg** [comment]
@andreracz I really appreciate the follow-up comment!  And agree 100%.  It looks like @abdullah248 was able to merge a fix for this issue. I validated the deployment works without App Insights, and will close this issue.  Please let me know if this remains an issue for you or others!
