### ISSUE TITLE
Assistance with setting up Azure DevOps for DICOM

### ISSUE THREAD

**Issue by CaitlinV39** [microsoft/dicom-server#443]
https://github.com/microsoft/fhir-server/issues/1409

A user had some questions about how to setup running a Azure DevOps server 2020 locally to build few OSS Repos that include Azure FHIR Server & Azure DICOM Server. We gave details on the FHIR OSS in the issue mentioned above but the user has questions about DICOM as well. I'm going to close out the issue on the FHIR Server and let the DICOM items be tracked here.

Thanks!

**Comment by StevenBorg** [comment]
Azure DevOps is a wonderful product, with a fantastic build system. It's what we use internally to verify builds of this OSS server as part of a CI/CD process. Our build files are available under the /builds directory, although they require effort to move to a different Azure subscription (such as setting up new permissions, etc).

We are considering a move to GitHub Actions, but that is not a priority at this time.  

For testing the latest Medical Imaging Server for DICOM in a simple fashion, or for building our a quick demo environment that runs locally, I recommend considering the docker-compose solution that builds out a DICOM, FHIR and DICOM Cast environment in only a few seconds.

Unfortunately, documenting the configuration of a per-user Azure DevOps build environment is out of scope at this time. Thus, I am closing this Issue.  Please feel free to comment, reactivate this issue, or create a new issue if you believe it was closed in error.
