### ISSUE TITLE
Wrong media type for Retrieve Instance transaction

### ISSUE THREAD

**Issue by hackermd** [microsoft/dicom-server#444]
**Describe the bug**
The [Retrieve Instance transaction](https://github.com/microsoft/dicom-server/blob/master/docs/resources/conformance-statement.md#retrieve-an-instance) of the DICOMweb service uses the wrong media type. It should be `multipart/related; type="application/dicom"` instead of `application/dicom`. See [DICOM Correction Proposal 2040](https://www.dicomstandard.org/news-dir/current/docs/cpack108/cp2040.pdf) for clarification.

**Comment by StevenBorg** [comment]
Thank you, @hackermd !  That certainly simplifies the retrieve transactions and makes all of them consistent with each other. We're looking into this now, and it certainly makes sense.  Thanks!  We'll keep you posted here.

**Comment by hackermd** [comment]
Great! Thanks for looking into it @StevenBorg

**Comment by StevenBorg** [comment]
@hackermd After some discussion, our take is that we should adopt the newer framework, even prior to acceptance under the standard, while still maintaining backward compatibility (in this case) for APIs which might be using the current standard. Do you see any concerns with this approach?

**Comment by hackermd** [comment]
No concerns. I agree that this would be the best approach.

The "newer" framework has actually always been the standard - at least it was supposed to. The goal of Supplement 183 was to refactor the documentation of Part 18 without actually changing the behavior. Unfortunately, a few things got broken and we are currently trying to correct those. However, since Supplement 183 was officially accepted, we should probably consider `application/dicom` to be standard compliant or at least support it in a backwards compatible manner. We are going to do the same client-side (see https://github.com/MGHComputationalPathology/dicomweb-client/pull/43).

**Comment by smithago** [comment]
Issue is fixed. Closing
