### ISSUE TITLE
Question: Plans for standalone packages?

### ISSUE THREAD

**Issue by edespong** [microsoft/dicom-server#453]
While this project is mainly for Azure deployments, I can see that the code is structured in such a way that there are parts that are completely Azure agnostic. Are there any plans of releasing such parts, for example, the Dicom.Core or Dicom.Client as official standalone NuGet packages?

I think that a stable and well functioning DICOMweb client library for .NET would be valuable for many that are not yet considering using the full blown project for example.

**Comment by StevenBorg** [comment]
We've certainly talked about pulling out the DICOMweb client library, as well as releasing portions of the solution as NuGet packages.  I'll restart that conversation and update this thread shortly with some of our thoughts.  Some dependencies might be hard to pull out, but a Dicom.Client NuGet could certainly make interacting with any DICOMweb system, including this one, far simpler for .NET developers.

**Comment by StevenBorg** [comment]
@edespong, I just wanted to cycle back to this comment!  I haven't forgotten about your request.  We've been very focused on getting the Azure Healthcare API hosted solution (which uses this as its underlying code) into general availability. I apologize for the delay, Erik.

**Comment by smithago** [comment]
closing as stale
