### ISSUE TITLE
Existing deployment breaking with latest deployment with asp.net core 5.0.2

### ISSUE THREAD

**Issue by premaarya** [microsoft/dicom-server#562]
**Describe the bug**
If I deploy the diacom-server to an existing instance using the latest [ARM Template ](https://github.com/microsoft/dicom-server/blob/master/samples/templates/default-azuredeploy.json), that upgrades the asp.net core runtime to 5.0.2 and processor to 64bit, I am getting error "HTTP Error 503. The service is unavailable.".
If I manually remove the exiting asp.net core runtime 3.1.X, it works. 
How to make it touchless deployment?

**To Reproduce**
1. Use the  latest [ARM Template ](https://github.com/microsoft/dicom-server/blob/master/samples/templates/default-azuredeploy.json)
2. Access the site :  https://dicom-websitename.azurewebsites.net.

**Expected behavior**
Default Page Or HTTP ERROR 404 - If Authentication/Authorization configured.
When I access the health API /api/dicom/health - should get response as {"Status" : "Healthy"}

**Actual behavior**
When I access the health API /api/dicom/health - getting the following error 

![image](https://user-images.githubusercontent.com/20116758/107541931-e2cef080-6b84-11eb-82ac-8c4de74ae9cc.png)

**Comment by KnicKnic** [comment]
We are working to provide better guidance, but currently the templates are for development purposes and do not work for upgrade. Please either redeploy the application or remove the old version of ASP.NET Core extensions from the webapp. We are also following up with the webapp team on best practices in regard to this issue.

**Comment by smithago** [comment]
closing, we have updated the readme to provide better guidance on the support
