### ISSUE TITLE
Fuzzy matching search (QIDO-RS) with dash in the patient's name

### ISSUE THREAD

**Issue by janossch** [microsoft/dicom-server#595]
**Describe the bug**
Query result could be misleading in case of fuzzy matching enabled and the patient's name contains a dash.
It could mislead the user in a sense that the user expects a result, but the query does not return any results.

An example patient name
> Atkinson - Lloyd^Alex

**To Reproduce**
1. Store a patient with patient name "Atkinson - Lloyd^Alex" (without the quotes)
2. Issue a query like this:  /studies?PatientName=Atkinson - Lloyd&FuzzyMatching=true

**Expected behavior**
Query should return back the Atkinson - Lloyd^Alex

**Actual behavior**
Result set is empty.

**Comment by smithago** [comment]
Thanks for reaching out with the issue. 

This will work
studies?PatientName=Atkinson Lloyd&FuzzyMatching=true

"-" is not indexed for fuzzy matching since it is not a word. Each word or term specified in PatientName value will be prefix matched to exist before returning matching study.

**Comment by janossch** [comment]
Thank your kind response.

If the hyphen isn't indexed why does this give back the result if we stay with the above example?
> studies?PatientName=Atkinson-Lloyd&FuzzyMatching=true

So for the patient name like:
> Atkinson - Lloyd^Alex

The fuzzy matching search:
- does not match: `Atkinson - Lloyd`
- matches: `Atkinson-Lloyd`

We operate on the basis of the user input, so what is your suggestion how we should design our search functionality if the above case occurs?
- Do we need to remove all occurrence of "-", or only if spaces around it? or
- Do we need to remove only the spaces around "-"? then
- What else do we need to remove e.g. "&"? or
- Am I on a completely wrong track and I need to start over and try to solve the problem differently?

**Comment by smithago** [comment]
Great question. 

For some details, behind the seen we use SQL full text search to support fuzzy matching.

We where doing some processing of the words specified as value for PatientName if they where separated by space. Looks like SQL parser already does that for us and it considers hypen as a word separator for ENU.

I have a PR to fix this . With that change hypen word breaker should work. Any SQL ENU word breaker like space, hypen, comma.. should all work.
will match: Atkinson - Lloyd
already matches: Atkinson-Lloyd
