### ISSUE TITLE
QIDO-RS. Required matching attributes

### ISSUE THREAD

**Issue by janossch** [microsoft/dicom-server#641]
DICOMweb standard has a statement for the required matching attributes:
*"The origin server shall support the matching Attributes specified in Table [10.6.1-5](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#table_10.6.1-5) for each supported IE Level."*

In contrast the conformance statement contains this [searchable attributes](https://github.com/microsoft/dicom-server/blob/main/docs/resources/conformance-statement.md#searchable-attributes) table, and it seems there are some deficiencies:

- Study Time
- Modalities In Study
- Study ID
- Series Number
- Performed Procedure Step Start Time
- Request Attributes Sequence
   - \>Scheduled Procedure Step ID
   - \>Requested Procedure ID
- SOP Class UID
- Instance Number

Based on the above some of the mandatory search attributes aren't supported by the server and as a consequence the solution doesn't conform with the standard. Is this assumption right?

**Comment by smithago** [comment]
That is correct and mentioned in our conformance. We are working a feature called "Extended query able tag" feature that will allow you to add any standard or private tags that you want to be available in QIDO

**Comment by janossch** [comment]
Thank you for your kind response! 
Really appreciate it, but please let me clarify one more question. 

Does this mean that the default set of attributes will also change?

If no, than I feel my question is still open, because you need to allow (or configure somehow) a few more attributes to let the solution be conform with the standard, right?
