### ISSUE TITLE
Deploy on privacy environment (VNet) not publish on internet

### ISSUE THREAD

**Issue by japineda3** [microsoft/dicom-server#737]
Hi,
I am trying to deploy this service on Azure with maximum privacy but I don´t know if it is possible to deploy the Dicom-server without use the arm template , because I would like to deploy the resources on Azure with privacy. For example, I would like to configure the security on SQL Azure to allow only connections by private endpoint not public endpoint as now ; I want to deploy the app service (DICOMWEB) with vnet integration and private endpoint, because the actual ARM template creates the app service with one IP in internet. The same with the rest of resources. . Please , anyone could help me with it? thanks.

**Comment by smithago** [comment]
Hello, The ARM template is just a sample to get test service running. You can create a similar template with VNET and private access to all the dependent azure resources.

**Comment by japineda3** [comment]
Hi
Thank you for you answer, but could you help more? Because I don't understand as I can put this information in the actual ARM because I see a lot of settings for app service. Also. I'd like to name the resources with nomenclature and you template doesn't leave me.
Thanks.

Enviado desde Yahoo Mail con Android 
 
  El vie., abr. 23, 2021 a 19:45, Smitha ***@***.***> escribió:   


Hello, The ARM template is just a sample to get test service running. You can create a similar template with VNET and private access to all the dependent azure resources.

**Comment by smithago** [comment]
Unfortunately we do not specific documentation on setting up all the dependents we have. But you can find help on each dependent service VNET configuration:
App service web app: https://docs.microsoft.com/en-us/azure/app-service/networking/private-endpoint
Storage account: https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-portal
Sql Server: https://docs.microsoft.com/en-us/azure/azure-sql/database/network-access-controls-overview

**Comment by smithago** [comment]
closing since not active in last week
