### ISSUE TITLE
Unable to access DICOM Api server after setting up with Docker Compose

### ISSUE THREAD

**Issue by pavankjadda** [microsoft/dicom-server#744]
**Describe the bug**
I setup local DICOM server and other components by following instructions from [here](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-via-docker.md), every thing starts fine but I can't access the API server. When I go to http://localhost:8080 I get HTTP 404 error(shown below in image)

**To Reproduce**
1. Clone the [repo](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-via-docker.md)
2. Start the applications using the command `env SAPASSWORD='Test@12345' docker-compose -f samples/docker/docker-compose.yaml -p dicom-server up -d`
3. Go to http://localhost:8080 to see the web page

**Expected behavior**
Application supposed to start and accessible from http://localhost:8080

**Actual behavior**
Webpage is not accessible and shows HTTP 404 error as shown below. However I do see API started in container logs
```
Hosting environment: Production

Content root path: /app

Now listening on: http://[::]:8080

Application started. Press Ctrl+C to shut down.
```
**Screenshot:**

<img width="1243" alt="Screen Shot 2021-04-27 at 7 04 47 PM" src="https://user-images.githubusercontent.com/17564080/116323310-b9892e00-a78b-11eb-95a7-93fc407aacb2.png">

**Comment by smithago** [comment]
Hello, the root url is not accessible. Supported request URLs are in the conformance statement here https://github.com/microsoft/dicom-server/blob/main/docs/resources/conformance-statement.md

**Comment by pavankjadda** [comment]
@smithago I don't understand what do you mean by root URL? The docker setup is not working. When I try to follow the instructions from [here](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-via-docker.md), it didn't work. Are the instructions are outdated?
