### ISSUE TITLE
 HTTP Error 500.30 - ASP.NET Core app failed to start

### ISSUE THREAD

**Issue by japineda3** [microsoft/dicom-server#761]
**Describe the bug**
I have deployed the last ARM template and I have this error. I deployed the ARM template on January on other azure resources and I didn´t have errors. I am thinking that there is a change on actual code or template that gives this error.

**To Reproduce**
1. Deploy the ARM tempalte on Azure
2. If you run the executable on the console on the web app , you see that the problem is because the framework version doesn´t exist.

** The diffence:
On the before app web service the extension is ASP NT core 3.1 
On the last app web service, the extension is ASP NET core 5.0.5

![image](https://user-images.githubusercontent.com/82374536/117308397-cbe92300-ae81-11eb-8162-6c77572b9949.png)

**Comment by smithago** [comment]
Hello, our latest template already installs the latest asp.net core 5.* version https://github.com/microsoft/dicom-server/blob/main/samples/templates/default-azuredeploy.json

Did you upgrade your existing deployment with a new webapp deployment? If so, here is a similar issue on how to fix it https://github.com/microsoft/dicom-server/issues/562

**Comment by japineda3** [comment]
Hello, I haven´t upgraded my existing deployment. I have two app web services differentes: One deployed with one release of January 2021 and other with the last ARM template. The first works ok with the ASP.NET extension 3.0.1 but the second doesn´t work with ASP.NET 5.0.5. 
I don´t understand why when I run the dicom.web.exe on the console of the app web service , it does show a message with says that it doesn´t find any compatible framework version, when the extension 5.0.5 is configure on the app web service as extension.
![image](https://user-images.githubusercontent.com/82374536/117637407-0f91a480-b182-11eb-9653-8e12f1f152b6.png)
![image](https://user-images.githubusercontent.com/82374536/117637481-1fa98400-b182-11eb-98b8-a2fbd8367bc0.png)

**Comment by smithago** [comment]
Maybe the path is not setup correctly. Does the webapp url work?

**Comment by japineda3** [comment]
Hi @smithago, could you say me where in the code you do the call to the secrets of key vault? Because, I want to use one keyvault for the two environments: production and developer.
I have tried to change the name of the secret: BlobStore--ConnectionString and then the web app doesn´t work.

**Comment by smithago** [comment]
Keyvalut is configures in Program.cs. The discussion is deviating from the original issue. I will close this Issue.

**Comment by walterqianTest1** [comment]
@japineda3 Maybe we have the same issue. You can refer to my ticket:https://github.com/microsoft/dicom-server/issues/801. Hope it helps.
