### ISSUE TITLE
"Bad request" when accessing the dicom server through the deployed OHIF viewer

### ISSUE THREAD

**Issue by fpaulano** [microsoft/dicom-server#800]
**Describe the bug**
We have deployed the project in Azure using the template and we encountered a "Bad request" error when accessing the viewer.

![imagen](https://user-images.githubusercontent.com/32868508/119798773-bc3a8880-bedb-11eb-8717-77d4c4621294.png)

**To Reproduce**
1. Deploy dicom-server in Azure using the provided template with default settings
2. Access to the deployed OHIF viewer using Chrome or Firefox browser.

**Expected behavior**
The OHIF viewer should display the list of studies

**Actual behavior**
JS crashes due to a bad request error.

**Comment by abdullah248** [comment]
Hi,
We tried reproducing this issue locally but were unable to. Can you try syncing from the latest code and then retrying? Hopefully that should resolve your issue.
