### ISSUE TITLE
DICOM web standard in Python Notebook broken

### ISSUE THREAD

**Issue by SimonBiggs** [microsoft/dicom-server#932]
Hi All,

I was just taking a squiz at this repo and as I was "driving by" I saw a few issues, figured I'd flag them so that you can be aware :slightly_smiling_face: .

---

The following notebook:

https://github.com/microsoft/dicom-server/blob/main/docs/resources/use-dicom-web-standard-apis-with-python.ipynb

Gives the following error message:

```
File Load Error for use-dicom-web-standard-apis-with-python.ipynb
Unreadable Notebook: /home/simon/Downloads/use-dicom-web-standard-apis-with-python.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')
```

Potentially it might be worth including the notebook examples within the testing suite with something like https://github.com/nteract/testbook?

---

Also, the link to the notebook from the markdown file gives a 404:

https://github.com/microsoft/dicom-server/blame/main/docs/tutorials/use-dicom-web-standard-apis-with-python.md#L3

Cheers :slightly_smiling_face:,
Simon

**Comment by abdullah248** [comment]
Hi @SimonBiggs,
Thanks for pointing these out! The jupyter notebook should work now and the link the documentation has been updated. 

Thanks!

**Comment by SimonBiggs** [comment]
Thanks Abdullah :), and my pleasure :)
